services:
  simplephpmvc-app:
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - mysql-db
    environment:
      MYSQL_DATABASE_SERVICE: mysql-db
      MYSQL_DATABASE: nw201402
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nw201402
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./recursos/nw201402.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql-data: